sudo: required
services:
  - docker

language: node_js

install:
  - docker build -t blog -f Dockerfile.deployment .
  - docker run -d blog

before_script:
  - npm install -g stylelint

script:
  - npm test

deploy:
  provider: script
  script: bash ./scripts/application_deploy $TRAVIS_TAG
  on:
    tags: true
    branch: master