sudo: required
services:
  - docker

language: node_js

install:
  - docker build -t blog -f Dockerfile.deployment .
  - docker run -d blog

script:
  - npm test

deploy:
  provider: script
  script: bash ./scripts/application_deploy
  on:
    branch: master