sudo: required
services:
  - docker

language: node_js
node_js:
  - "node"

before_install:
  - docker build -t blog -f Dockerfile.deployment .
  - docker run -d blog

install:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker tag blog $DOCKER_IMAGE:v$TRAVIS_TAG
  - docker push $DOCKER_IMAGE:v$TRAVIS_TAG;
  - docker run -d $DOCKER_IMAGE:v$TRAVIS_TAG

before_script:
  - npm install -g stylelint
  - npm install stylelint-config-sevenval

script:
  - npm test

deploy:
  provider: script
  script: bash ./scripts/application_deploy $TRAVIS_TAG
  on:
    tags: true
    branch: master