sudo: required
services:
  - docker

language: ruby

before_install:
  - docker build -t blog -f Dockerfile.deployment .
  - docker run -d blog

deploy:
  provider: script
  script: bash ./scripts/application_deploy
  on:
    branch: master