FROM quelltexterin/hugo:v1.0.0 as builder

RUN mkdir -p /var/www/blog

COPY site /var/www/blog/
COPY deployment/ /etc/nginx/sites-available/

WORKDIR /var/www/blog

RUN hugo -d public --templateMetrics --debug

FROM nginx:1.13-alpine
COPY --from=builder /var/www/blog/public/ /usr/share/nginx/html