version: '3'

services:
  npm:
    image: node:6-alpine
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: "npm build"
  hugo:
    image: yanqd0/hugo
    volumes:
      - ./site:/srv/hugo
    ports:
      - 1313:1313