version: '3'

services:
  npm:
    image: node:6-alpine
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: "npm start"
  hugo:
    image: quelltexterin/blog:v0.5.0
    volumes:
      - ./site:/var/www/blog
    working_dir: /var/www/blog
    command: hugo server --bind=0.0.0.0
    ports:
      - 1313:1313
