version: v1
project: quelltexterin
services:
  frontend:
    hugo:
      image: $docker_image
      domain: $domain
      port: 80
      ssl: true
      env:
        - HAPROXY_0_REDIRECT_TO_HTTPS : "true"