#!/usr/bin/env bash
set -e
set -x

curl -L https://files.sloppy.io/sloppy-`uname -s`-`uname -m` > sloppy

chmod +x sloppy

./sloppy change -v docker_image:"$DOCKER_IMAGE:v$TRAVIS_TAG" -v domain:"$DOMAIN" $SLOPPY_FILE